name: PR Validation

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    env:
      QDRANT_CONNECTION_STRING: ${{ secrets.CI_QDRANT_URL }}
      OXIGRAPH_CONNECTION_STRING: ${{ secrets.CI_OXIGRAPH_URL }}
      OPENAI_API_KEY: ${{ secrets.CI_OPENAI_API_KEY }}
      EMBEDDING_MODEL: ${{ secrets.CI_EMBEDDING_MODEL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Cargo Check
        run: cargo check --all-targets

      - name: Cargo Test
        run: cargo test --verbose

      - name: Clippy Check
        run: cargo clippy --all-targets -- -D warnings
